import React from 'react';

export const specsCtx = React.createContext({
  distance: 'less than 2m',
  wideangle: false,
  mainUse: 'Movies',
  usageTime: 'Daytime',
  brightness: 'bright',
  androidTv: false,
  googleCast: false,
  airPlay: false,
  smartHomeControl: false,
  oneRemote: false,
  advancedGameMode: false,
  priceRange: 'high-end',
  dislikedLg: true,
  dislikedPanasonic: false,
  dislikedSamsung: false,
  dislikedSony: false,
  dislikedTcl: false,
  dislikedTpv: false,
  dvbt: false,
  dvbc: false,
  dvbs: false,
  twinTuner: false,
  hdmis: '4',
  headphoneJack: false,
  hdmi20: false,
  bluetooth: false
});
