import React from 'react';

export const specsCtx = React.createContext({
  distance: '',
  wideangle: false,
  mainUse: '',
  usageTime: '',
  brightness: '',
  androidTv: false,
  googleCast: false,
  airPlay: false,
  smartHomeControl: false,
  oneRemote: false,
  advancedGameMode: false,
  priceRange: '',
  dislikedLg: true,
  dislikedPanasonic: false,
  dislikedSamsung: false,
  dislikedSony: false,
  dislikedTcl: false,
  dislikedTpv: false,
  dvbt: false,
  dvbc: false,
  dvbs: false,
  twinTuner: false,
  hdmis: '4',
  headphoneJack: false,
  hdmi20: false,
  bluetooth: false
});
